### PR TITLE
Year updated

### PR DESCRIPTION
**Pull request by megha12367**
i have updated the year from 2016 to 2019

### CODE REVIEW

**Review by LeSpocky — CHANGES_REQUESTED** [review]
Thanks for this pull request. However, as far as I understood these licensing issues, this is not correct. There have to be all that years in which the code of the project was changed. For this project this is currently 2016 only. If someone makes new changes, new years can be added. Years once in this list, are not removed.

**Comment by penguineer** [comment]
> Thanks for this pull request. However, as far as I understood these licensing issues, this is not correct. There have to be all that years in which the code of the project was changed. For this project this is currently 2016 only. If someone makes new changes, new years can be added. Years once in this list, are not removed.

I agree with LeSpocky. If you make changes to this project, 2019 may be added here, but 2016 needs to stay.

**Review by penguineer — CHANGES_REQUESTED** [review]
I appreciate the contribution, but in this case I vote to decline the PR.

**Comment by LeSpocky** [comment]
> I appreciate the contribution, but in this case I vote to decline the PR.

On second sight, it looked like spam or someone getting easy PR merged for hacktoberfest? I close this.

**Comment by penguineer** [comment]
Yes, looks like hacktoberfest.

**Pull request closed without merging**
